### ISSUE TITLE
not an issue - thoughts on float vs double 

### ISSUE THREAD

**Issue by johndpope** [morpheby/Seconn-Swift#5]
https://teamtreehouse.com/community/what-is-the-benefit-of-using-float-instead-of-double
I've been digging through the code and attempting to simplify some things. Seems like Double is the way to go. 

P.S. - I like how the layers in this code base is setup / rather than tracking separate hidden layers. 
the  Neurons also become a NeuronBias 

```swift
class Layer {
    let previousLayer: Layer?
    var neurons: [Neuron]
    var outputCache: [Double]
    var hasBias: Bool = false
    
    // for future use in deserializing networks
    init(previousLayer: Layer? = nil, neurons: [Neuron] = [Neuron]()) {
        self.previousLayer = previousLayer
        self.neurons = neurons
        self.outputCache = Array<Double>(repeating: 0.0, count: neurons.count)
    }
    
    // main init
    init(previousLayer: Layer? = nil, numNeurons: Int, activationFunction: @escaping (Double) -> Double, derivativeActivationFunction: @escaping (Double)-> Double, learningRate: Double, hasBias: Bool = false) {
        self.previousLayer = previousLayer
        self.neurons = Array<Neuron>()
        self.hasBias = hasBias
        for _ in 0..<numNeurons {
            self.neurons.append(Neuron(weights: randomWeights(number: previousLayer?.neurons.count ?? 0), activationFunction: activationFunction, derivativeActivationFunction: derivativeActivationFunction, learningRate: learningRate))
        }
        if hasBias {
            self.neurons.append(BiasNeuron(weights: randomWeights(number: previousLayer?.neurons.count ?? 0)))
        }
        self.outputCache = Array<Double>(repeating: 0.0, count: neurons.count)
    }
    
    func outputs(inputs: [Double]) -> [Double] {
        if previousLayer == nil { // input layer (first layer)
            outputCache = hasBias ? inputs + [1.0] : inputs
        } else { // hidden layer or output layer
            outputCache = neurons.map { $0.output(inputs: inputs) }
        }
        return outputCache
    }
    
    // should only be called on an output layer
    func calculateDeltasForOutputLayer(expected: [Double]) {
        for n in 0..<neurons.count {
            neurons[n].delta = neurons[n].derivativeActivationFunction( neurons[n].inputCache) * (expected[n] - outputCache[n])
        }
    }
    
    // should not be called on output layer
    func calculateDeltasForHiddenLayer(nextLayer: Layer) {
        for (index, neuron) in neurons.enumerated() {
            let nextWeights = nextLayer.neurons.map { $0.weights[index] }
            let nextDeltas = nextLayer.neurons.map { $0.delta }
            let sumOfWeightsXDeltas = dotProduct(nextWeights, nextDeltas)
            neuron.delta = neuron.derivativeActivationFunction( neuron.inputCache) * sumOfWeightsXDeltas
        }
    }
    
    
}

```
https://github.com/davecom/SwiftSimpleNeuralNetwork/

**Comment by morpheby** [comment]
It would be interesting to try out. You can just change FloatType definition to Double, it’s in the file Network.swift on line 11 and see what comes out.

Code you are referencing uses sequential operations for computation. That allows some interesting approaches, but also severely limits performance — almost no modern neural networks today use this, instead using OpenCL, TensorFlow, or just BLAS (like I am here) to perform matrix operations instead of sequential, which are faster. Such approaches limit options for the best design, and one reason is that basically the more tightly the data is packed and the easiest it is to follow without branching for CPU — the better. I tried to put most of the computation without `if`s and instead rely on direct flows and numeric logic. I’ve done some performance testing while developing and my results showed that this is the best approach to maintain speed. Besides, this principle is in fact the basis for TensorFlow.

**Comment by johndpope** [comment]
fyi - https://github.com/saschaschramm/SwiftReinforce (not working with yesterday's swift tensorflow) but does work with latest months build.

**Comment by morpheby** [comment]
Thank you. I wish to play with Swift TensorFlow, and maybe redo this in TensorFlow, but I decided to wait for at least Xcode 10 release. I have bad experience with betas in my production workflow.

**Comment by johndpope** [comment]
this "official" swift code for tensorflow is stable 
https://github.com/tensorflow/swift-models/blob/stable/MNIST/MNIST.swift

**Comment by johndpope** [comment]
FYI - https://github.com/tanmayb123/OpenAI-Unsupervised-Sentiment-Neuron---Swift-for-TensorFlow
